---
version: 1.1.x.{build}
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
  - SET
  - 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
environment:
  matrix:
    -
      RUBY_VERSION: 24-x64
    -
      PUPPET_GEM_VERSION: ~> 4.6
      RUBY_VERSION: 21
    -
      PUPPET_GEM_VERSION: ~> 4.6
      RUBY_VERSION: 21-x64
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24-x64
matrix:
  fast_finish: true
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install --jobs 4 --retry 2 --without system_tests
  - type Gemfile.lock
build: off
test_script:
  - bundle exec puppet -V
  - ruby -v
  - gem -v
  - bundle -v
  - bundle exec rake test
notifications:
  - provider: Email
    to:
      - nobody@nowhere.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
